apiVersion: v1
kind: Pod
metadata:
  name: app-store
  labels:
    app: app-store
spec:
  containers:
  - name: app-store
    image: adrian31s/app-store:1.0.13
    imagePullPolicy: Always
    env:
      - name: DB_URL
        valueFrom:
          configMapKeyRef:
            name: services-config
            key: DB_URL
      - name: DB_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: services-config
            key: DB_PASSWORD
      - name: DB_USER
        valueFrom:
          configMapKeyRef:
            name: services-config
            key: DB_USER
      - name: HIBERNATE_GENERATION
        valueFrom:
          configMapKeyRef:
            name: services-config
            key: HIBERNATE_GENERATION
      - name: QUARKUS_LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: services-config
            key: QUARKUS_LOG_LEVEL      
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          configMapKeyRef:
            name: sensitive-services-config
            key: AWS_ACCESS_KEY_ID  
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          configMapKeyRef:
            name: sensitive-services-config
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_BUCKET_NAME
        valueFrom:
          configMapKeyRef:
            name: sensitive-services-config
            key: AWS_BUCKET_NAME                 
    ports:
    - containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
  name: app-store
spec:
  selector:
    app: app-store
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 8080  
      nodePort: 30001
  type: NodePort  
