apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: appstore
  POSTGRES_USER: store-user 
  POSTGRES_PASSWORD: store-password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: services-config
data:
  POSTGRES: postgresdb
  DB_URL: jdbc:postgresql://postgresdb/appstore
  DB_PASSWORD: store-password
  DB_USER: store-user
  HIBERNATE_GENERATION: drop-and-create
  QUARKUS_LOG_LEVEL: debug